export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1 style={{ background: "green", height: "50vh" }}>
            this is header
          </h1>
        </header>
        {children}
        <footer>
          <h1 style={{ background: "gray", height: "50vh" }}>
            this is a footer
          </h1>
        </footer>
      </body>
    </html>
  );
}
