export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* body then header then children then footer */}
      <body>
        <header>
          <h1 style={{ background: "green" }}>this is header</h1>
        </header>
        {children}
        <footer>
          <h1 style={{ background: "gray" }}>this is a footer</h1>
        </footer>
      </body>
    </html>
  );
}
